# Generated by Django 6.0.2 on 2026-02-21 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Terem neve')),
                ('capacity', models.PositiveIntegerField(verbose_name='Férőhelyek száma')),
                ('rows', models.PositiveIntegerField(verbose_name='Sorok száma')),
                ('seats_per_row', models.PositiveIntegerField(verbose_name='Székek soronként')),
            ],
            options={
                'verbose_name': 'Moziterem',
                'verbose_name_plural': 'Mozitermek',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cím')),
                ('description', models.TextField(verbose_name='Leírás')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Időtartam (perc)')),
                ('genre', models.CharField(max_length=100, verbose_name='Műfaj')),
                ('director', models.CharField(max_length=200, verbose_name='Rendező')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Poszter')),
                ('release_date', models.DateField(verbose_name='Megjelenés dátuma')),
                ('age_rating', models.CharField(blank=True, max_length=10, verbose_name='Korhatár')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmek',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Kezdés időpontja')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jegyár (Ft)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktív')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.cinemahall', verbose_name='Terem')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.movie', verbose_name='Film')),
            ],
            options={
                'verbose_name': 'Vetítés',
                'verbose_name_plural': 'Vetítések',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Vendég e-mail')),
                ('guest_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vendég telefonszám')),
                ('seat_row', models.PositiveIntegerField(verbose_name='Sor')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Szék')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Vásárlás dátuma')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Törölve')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Ellenőrizve')),
                ('ticket_code', models.CharField(max_length=20, unique=True, verbose_name='Jegykód')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.screening', verbose_name='Vetítés')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Eladta')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ellenőrizte')),
            ],
            options={
                'verbose_name': 'Jegy',
                'verbose_name_plural': 'Jegyek',
                'ordering': ['-purchase_date'],
                'unique_together': {('screening', 'seat_row', 'seat_number')},
            },
        ),
    ]
