# Generated by Django 6.0.2 on 2026-02-21 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Férőhelyek száma'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='rows',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Sorok száma'),
        ),
        migrations.AlterField(
            model_name='cinemahall',
            name='seats_per_row',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Székek soronként'),
        ),
        migrations.AlterField(
            model_name='screening',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jegyár (Ft)'),
        ),
    ]
