# Generated by Django 6.0.2 on 2026-02-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cinemahall_capacity_alter_cinemahall_rows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Poszter URL'),
        ),
    ]
