# Generated by Django 6.0.2 on 2026-02-21 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_movie_poster_movie_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='capacity',
            field=models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Férőhelyek száma'),
        ),
    ]
