# Generated by Django 6.0.2 on 2026-02-24 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cinemahall_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active', '-release_date'], name='idx_movie_active_date'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='idx_movie_title'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['is_active', 'start_time'], name='idx_screening_active_time'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['movie', 'is_active', 'start_time'], name='idx_screening_movie_time'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['hall', 'start_time'], name='idx_screening_hall_time'),
        ),
        migrations.AddIndex(
            model_name='screening',
            index=models.Index(fields=['start_time'], name='idx_screening_time'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['screening', 'is_cancelled'], name='idx_ticket_screening_cancel'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_code'], name='idx_ticket_code'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'is_cancelled'], name='idx_ticket_user_cancel'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['purchase_date'], name='idx_ticket_purchase_date'),
        ),
    ]
