# Generated by Django 6.0.2 on 2026-02-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_idx_movie_active_date_movie_idx_movie_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date'], 'permissions': [('manage_movies', 'Filmek kezelése')], 'verbose_name': 'Film', 'verbose_name_plural': 'Filmek'},
        ),
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['start_time'], 'permissions': [('manage_screenings', 'Vetítések kezelése')], 'verbose_name': 'Vetítés', 'verbose_name_plural': 'Vetítések'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-purchase_date'], 'permissions': [('sell_tickets', 'Jegyek eladása (pénztár)'), ('verify_tickets', 'Jegyek ellenőrzése')], 'verbose_name': 'Jegy', 'verbose_name_plural': 'Jegyek'},
        ),
    ]
